### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'required'

### ISSUE THREAD

**Issue by beli68** [manchenkoff/openapi3-parser#19]
Get the file from the [swagger-petstore](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml) and save it as petstore.yml.

I get an error when I run the code below.

```python
from openapi_parser import parse

a = parse('./petstore.yml')
```

Looking at the debug messages, `builders` are working fine until halfway through, so is it a problem with the yaml file?
Thanks in advance.

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspaces/learn_owl/openapi.py", line 3, in <module>
    a = parse('./petstore.yml')
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/parser.py", line 118, in parse
    return parser.load_specification(specification)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/parser.py", line 63, in load_specification
    attrs = extract_typed_props(data, attrs_map)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 33, in extract_typed_props
    custom_attrs = {
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 34, in <dictcomp>
    attr_name: cast_value(attr_info.name, data[attr_info.name], attr_info.cast)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 26, in cast_value
    return type_cast_func(value) \
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/path.py", line 21, in build_list
    return [
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/path.py", line 22, in <listcomp>
    self._build_path(url, path)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/path.py", line 39, in _build_path
    attrs["operations"] = [
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/path.py", line 40, in <listcomp>
    self.operation_builder.build(method, data[method.value])
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/operation.py", line 44, in build
    attrs = extract_typed_props(data, attrs_map)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 33, in extract_typed_props
    custom_attrs = {
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 34, in <dictcomp>
    attr_name: cast_value(attr_info.name, data[attr_info.name], attr_info.cast)
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/common.py", line 26, in cast_value
    return type_cast_func(value) \
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/parameter.py", line 19, in build_list
    return [self.build(parameter) for parameter in parameters]
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/parameter.py", line 19, in <listcomp>
    return [self.build(parameter) for parameter in parameters]
  File "/workspaces/learn_owl/.venv/lib/python3.9/site-packages/openapi_parser/builders/parameter.py", line 35, in build
    return Parameter(**attrs)
TypeError: __init__() missing 1 required positional argument: 'required'
```

</details>

**Comment by manchenkoff** [comment]
Hi, it seems like an error while parsing, I'll check it and return with details

**Comment by manchenkoff** [comment]
@beli68 I've just fixed some problems with parser by extending enumeration of ContentTypes to support application/octet-stream and making `required` property of request parameter optional, now it should work fine.

Anyway, you should replace `default` responses with some HTTP codes like 200, 404, etc because it's unconvertible to Python dictionary correctly.

**Comment by beli68** [comment]
@manchenkoff 
Thank you for the swift response.
I think it would be better to support `default` in the future because it is a description allowed by the OAS.

**Comment by manchenkoff** [comment]
@beli68 yeah, I'll fix it in another issue
