### ISSUE TITLE
[BUG] StringFormat needs URL?

### ISSUE THREAD

**Issue by arquicanedo** [manchenkoff/openapi3-parser#59]
**Describe the bug**
I'm trying to parse the 1password yaml spec (https://api.apis.guru/v2/specs/1password.local/connect/1.5.7/openapi.yaml). Openapi3-parser failed with this error.

```
Traceback (most recent call last):
  File "c:\xxx\.conda\lib\site-packages\openapi_parser\builders\common.py", line 22, in cast_value
    return type_cast_func(value) \
  File "c:\xxx\.conda\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "c:\xxx\.conda\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'url' is not a valid StringFormat
```

Adding `URL` to `StringFormat` in `enumeration.py` does the trick. Not sure if this is not supposed to be this way but now I'm able to parse this file.

```
@unique
class StringFormat(Enum):
    BYTE = 'byte'
    BINARY = 'binary'
    DATE = 'date'
    DATETIME = 'date-time'
    PASSWORD = 'password'
    UUID = 'uuid'
    EMAIL = 'email'
    URI = 'uri'
    URL = 'url'
```

**To Reproduce**
1.     `specification = parse('collection/1password.yaml')`

**Expected behavior**
Correctly parse this spec.

**System details (please complete the following information):**
 - OS: Windows10
 - OpenAPI 3.0.2
 - Python version 3.10

**Additional context**
None

**Comment by manchenkoff** [comment]
Published as v1.1.10
